import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../src/components/Navbar";

import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });
import SessionProvider from "../src/utils/SessionProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
        <div className="mx-auto max-w-5xl text-xl gap-10 m-10">
          <Navbar />
          {children}
        </div>
        </SessionProvider>
      </body>
    </html>
  );
}
